spring:
  profiles:
    active: keys
  application:
    name: game-market

application:
  key-service:
    base-path: http://localhost:8081
    keys: ${application.key-service.base-path}/key-service/v1/activate
  feature:
    toggles:
      key-activation: false
      summer-sale: false
---
spring:
  config:
    activate:
      on-profile: keys
application:
  key-service:
    base-path: http://localhost:8081
    keys: ${application.key-service.base-path}/key-service/v1/activate
  feature:
    toggles:
      key-activation: true
      summer-sale: true

