logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client: DEBUG
spring:
  profiles:
    active: keys
  application:
    name: game-market
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS256
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        jdbc.batch_size: 15
        order_inserts: true
        order_updates: true
        query.fail_on_pagination_over_collection_fetch: true
        query.in_clause_parameter_padding: true
        connection.provider_disables_autocommit: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5555/mydatabase
    username: user
    password: password
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true
application:
  key-service:
    base-path: http://localhost:8081
    keys: ${application.key-service.base-path}/key-service/v1/activate
  feature:
    toggles:
      key-activation: false
      summer-sale: false
---
spring:
  config:
    activate:
      on-profile: keys
application:
  key-service:
    base-path: http://localhost:8081
    keys: ${application.key-service.base-path}/key-service/v1/activate
  feature:
    toggles:
      key-activation: true
      summer-sale: true

